### ISSUE TITLE
top variables break es6 imports

### ISSUE THREAD

**Issue by scottrblock** [scripting/opmlToJs#2]
the way `myProductName` and `myProductVersion` are declared - https://github.com/scottrblock/opmlToJs/blob/master/opmltojs.js#L1 -  does not work when the package is built with parcel. I forked this locally, and changed the line in question to `const myProductName = "opmltojs", myVersion = "0.4.10"` and it fixed the issue.

I don't know much about the internals of parcel to know what it's doing, but I know including npm package `opml`, which requires this package, and running `parcel build --public-url . --no-source-maps index.html` creates a built js file that produces this error:
![image](https://user-images.githubusercontent.com/1139703/163864829-8b528161-877e-4dc6-8f5f-89a14aaf8e1a.png)

of note, this is how you're already doing it in the `opmlPackage` project - https://github.com/scripting/opmlPackage/blob/main/opmlpackage.js#L1

this is needed to build the logseq plugin i'm working on.

**Comment by scripting** [comment]
1. I don't know what parcel is.
2. What are you trying to do? Is this problem in the Node.js package or the client code.
3. What is it that it doesn't like about the global declaration. It's completely legal JS in either context as far as I know.
4. If you're ok with forking it, i'm okay, except you won't get any bug fixes or new features. Not that there are any contemplated at this time.

**Comment by scottrblock** [comment]
1) [parcel](https://parceljs.org/) is a JS build tool, and is used in the [logseq sample plugins](https://github.com/logseq/logseq-plugin-samples/blob/master/logseq-reddit-hot-news/package.json#L15-L18), so it's what i've been using for logseq plugin development.
2) I'm trying to include the `opml` npm package in a logseq plugin - https://github.com/phonetonote/tft-interop/blob/main/logseq-opml-drummer/index.ts#L4, so that I can use it to [stringify the opml file](https://github.com/phonetonote/tft-interop/blob/main/logseq-opml-drummer/index.ts#L47). The code gets built by parcel and is then run in the browser.
3) I'm not sure, but the minified js that parcel builds isn't valid
4) I think this would be better off being changed in the original package so that its easier for others to import into future logseq plugins, but I'm happy to fork it.

**Comment by scripting** [comment]
What’s the change that needs to be made in my code?

**Comment by scottrblock** [comment]
change first line in https://github.com/scripting/opmlToJs/blob/master/opmltojs.js from `var myProductName = "opmltojs"; myVersion = "0.4.10";` to `var myProductName = "opmltojs", myVersion = "0.4.10";`

**Comment by scripting** [comment]
I made the [change](https://github.com/scripting/opmlToJs/blob/master/opmltojs.js#L1), resulting in v0.4.12 of opmlToJs.

**Comment by scottrblock** [comment]
cool thanks, will pull that down!
